### ISSUE TITLE
Cannot run development server DEV is not recognized and src/index.ts module not found

### ISSUE THREAD

**Issue by AntonioRitucci** [solana-labs/chatgpt-plugin#15]
As mentioned in the title:
Runned yarn in the root project directory.
Windows 10
Node 20.2.0
Yarn 1.22.19
yarn dev: result ->   DEV not recognized
yarn start: result -> module src/index.ts not found 

What I am doing wrong?
Thanks

**Comment by ngundotra** [comment]
Oops, sorry run it from `chatgpt-plugin`, not root. Will update
